[package]
name = "lambda"
version = "0.1.0"
authors = ["Sahan Fernando <sahan.h.fernando@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.14.0"

[dependencies]
lalrpop-util = "0.14.0"
regex = "0.2.1"
