[package]
name = "lambda"
version = "0.1.0"
authors = ["Sahan Fernando <sahan.h.fernando@gmail.com>"]

[build-dependencies]
lalrpop = { version = "0.19.7", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.7"
regex = "^1.5.5"
